name: feature-pipeline-frontend

on: [push]
permissions:
  contents: read
  statuses: write
  security-events: read

jobs:
  feature-pipeline:
    if: github.ref != 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/dummy-feature-frontend.yml@main
    with:
      project: expense-project
      component: frontend
      environment: dev
    secrets: inherit  

  dev-pipeline:
    if: github.ref == 'refs/heads/main'
    uses: tata-actions/workflows/.github/workflows/dummy-dev-frontend.yml@main
    with:
      project: expense-project
      component: frontend
      environment: dev
    secrets: inherit    

  
    
